name: Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-development:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-core

      - name: Build and start services with docker compose
        run: |
          docker compose --profile cpu up --build -d
          sleep 5  # Wait for services to start

      - name: Show server logs
        run: docker compose logs cyber-query-ai

      - uses: ./.github/actions/docker-check-containers
        with:
          port: 443

      - name: Stop services
        run: docker compose down

  docker-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-core

      - name: Build production image
        run: |
          docker build -t cyber-query-ai:prod .

      - name: Start services with docker compose
        run: |
          docker compose --profile cpu up -d
          sleep 5  # Wait for container to start

      - name: Show server logs
        run: docker logs cyber-query-ai

      - uses: ./.github/actions/docker-check-containers
        with:
          port: 443

      - name: Stop services
        run: docker compose down
